const ALLOWED_ORIGINS = [
  "https://localleadforge.com",
  "https://www.localleadforge.com",
];

const TEST_EMAILS = [
  "info@localleadforge.com",
  "localleadforgeagency@gmail.com",
];

const ALLOWED_PROSPECT_DOMAINS = [
  "wadeheating.com",
  "newlevelmechanical.com",
];

function cors(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}

function json(data, status, origin) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "Content-Type": "application/json",
      ...cors(origin),
    },
  });
}

function clean(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function emailAllowed(email) {
  const e = email.toLowerCase().trim();
  return (
    TEST_EMAILS.includes(e) ||
    ALLOWED_PROSPECT_DOMAINS.some((domain) => e.endsWith(`@${domain}`))
  );
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";

    if (!ALLOWED_ORIGINS.includes(origin)) {
      return new Response("Forbidden", { status: 403 });
    }

    if (request.method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: cors(origin),
      });
    }

    if (request.method !== "POST") {
      return json({ error: "Method not allowed" }, 405, origin);
    }

    let lead;

    try {
      lead = await request.json();
    } catch {
      return json({ error: "Invalid JSON" }, 400, origin);
    }

    const {
      name,
      phone,
      issue,
      location,
      timing,
      language,
      demoEmail,
    } = lead;

    if (
      !name ||
      !phone ||
      !issue ||
      !location ||
      !timing ||
      !language ||
      !demoEmail
    ) {
      return json({ error: "Missing lead information" }, 400, origin);
    }

    const email = String(demoEmail).trim().toLowerCase();

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return json({ error: "Invalid email" }, 400, origin);
    }

    if (!emailAllowed(email)) {
      return json(
        { error: "Please use an approved prospect or Local Lead Forge test email address." },
        403,
        origin,
      );
    }

    if (!env.RESEND_API_KEY) {
      return json({ error: "Email service unavailable" }, 500, origin);
    }

    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Local Lead Forge Demo <demo@localleadforge.com>",
        to: [email],
        subject: `Demo Website Lead — ${name} — ${location}`,
        text: `
LOCAL LEAD FORGE
DEMO WEBSITE LEAD

Customer: ${name}
Phone: ${phone}
HVAC issue: ${issue}
Location: ${location}
Requested timing: ${timing}
Language: ${language}

This is a demonstration lead generated through a personalized Local Lead Forge preview.

In a live installation, leads like this can be delivered automatically to your team, including leads captured outside normal business hours.

Local Lead Forge
https://localleadforge.com
        `,
        html: `
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#183b45">
  <div style="background:#183b45;color:white;padding:24px;border-radius:12px 12px 0 0">
    <div style="color:#f47735;font-size:12px;font-weight:bold">
      LOCAL LEAD FORGE
    </div>
    <h1>DEMO WEBSITE LEAD</h1>
  </div>

  <div style="padding:28px;border:1px solid #ddd">
    <p>This is what a qualified website lead could look like when delivered automatically to your team.</p>

    <p><strong>Customer:</strong> ${clean(name)}</p>
    <p><strong>Phone:</strong> ${clean(phone)}</p>
    <p><strong>HVAC issue:</strong> ${clean(issue)}</p>
    <p><strong>Location:</strong> ${clean(location)}</p>
    <p><strong>Requested timing:</strong> ${clean(timing)}</p>
    <p><strong>Language:</strong> ${clean(language)}</p>

    <a href="tel:${clean(phone)}"
       style="display:block;background:#f47735;color:#183b45;text-decoration:none;text-align:center;padding:14px;border-radius:30px;font-weight:bold;margin-top:24px">
       CALL CUSTOMER
    </a>

    <p style="margin-top:28px;font-size:13px;color:#666">
      Demo generated by <strong>Local Lead Forge</strong>.
      In a live installation, website leads can be delivered automatically to your team for follow-up.
    </p>
  </div>
</div>
        `,
      }),
    });

    if (!response.ok) {
      console.error("Resend error:", await response.text());
      return json({ error: "Unable to send demo email" }, 500, origin);
    }

    return json({ success: true }, 200, origin);
  },
};
